apiVersion: v1
data:
  ARQUIVO_ALERTAS: alertas.jsonl
  ARQUIVO_DADOS: dados-processados.jsonl
  AUTO_COMMIT_INTERVAL_MS: "5000"
  DIR_DADOS: /dados
  ENERGIA_LIMITE: "200.0"
  ENERGIA_MAX: "220.0"
  ENERGIA_MIN: "50.0"
  GRUPO_CONSUMIDORES: processadores
  HEARTBEAT_INTERVAL_MS: "3000"
  INTERVALO_SEGUNDOS: "2"
  KAFKA_BOOTSTRAP: kafka-1-0.kafka-headless:9092,kafka-2-0.kafka-headless:9092,kafka-3-0.kafka-headless:9092
  MAX_POLL_INTERVAL_MS: "300000"
  PARTICOES: "3"
  PERSISTENCIA_ATIVA: "true"
  REPLICACAO: "3"
  SESSION_TIMEOUT_MS: "10000"
  TEMP_LIMITE: "50.0"
  TEMP_MAX: "55.0"
  TEMP_MIN: "15.0"
  TOPICO_SENSORES: dados-sensores
  UMIDADE_LIMITE: "80.0"
  UMIDADE_MAX: "90.0"
  UMIDADE_MIN: "35.0"
  VIBRACAO_LIMITE: "10.0"
  VIBRACAO_MAX: "12.0"
  VIBRACAO_MIN: "0.0"
kind: ConfigMap
metadata:
  name: fabrica-config
  namespace: fabrinteligente
